### ISSUE TITLE
Support Selenium WebDriver Options for Firefox and Chrome

### ISSUE THREAD

**Issue by bpconkord** [readiness-it/qat-web#27]
Add support for options browser configuration via browsers.yml file. Example:

```
default_browser:
  browser: firefox
  screen: screen_1080p
  options:
    args:
      - '--headless'
    preferences:
      geo.enabled: false
      accept_insecure_certs: true
```
